alias gst="git status"
alias gco="git checkout"
alias gd="git diff"
alias ggpull="git pull"
alias ggpush="git push"
alias glg="git log"
alias gds="git diff --staged"
alias ggpushf="git push -f"
alias gb="git branch"
alias gnew="git checkout -b"
alias gcm="git commit -m"

alias ls="ls --color -a"

alias bashrc="$EDITOR ~/.bashrc"
alias rcsync="source ~/.bashrc"
